export const NAIROBI_WISDOM = [
  { number: 1, title: "The Nairobi Spirit", lesson: "Nairobi is the only city where a traffic jam is a legitimate social event and a business opportunity for hawkers." },
  { number: 2, title: "Matatu Culture", lesson: "If your matatu doesn't have at least 15 screens, a sub-woofer that shakes the ground, and a DJ, is it even a matatu?" },
  { number: 3, title: "The Nairobi Hustle", lesson: "In Nairobi, everyone has a 'guy' for everything. If you don't have a guy, you are the person someone else calls 'my guy'." },
  { number: 4, title: "Kanjo Logic", lesson: "The fastest runners in Kenya aren't from Iten; they are Nairobi hawkers when they hear the Kanjo siren." },
  { number: 5, title: "Nairobi Time", lesson: "'Nakuja' means I haven't left the house. 'Niko karibu' means I've just reached the stage. 'Niko hapo nje' means I'm 10 minutes away." },
  { number: 6, title: "Culinary Truths", lesson: "Safe passage through Nairobi traffic is best fueled by a 'smokie-pasua' with extra kachumbari." },
  { number: 7, title: "The Shortcut Rule", lesson: "A Nairobi shortcut will either save you an hour or lead you into a scenic tour of a neighborhood you didn't know existed." },
  { number: 8, title: "Weather Report", lesson: "Nairobi weather is like a toxic relationship: It will give you sunshine at 10 AM and a thunderstorm at 10:05 AM." },
  { number: 9, title: "CBD Parking", lesson: "If you find a parking spot in CBD at noon, look around—it's either a trap or you're dreaming." },
  { number: 10, title: "Matatu Ethics", lesson: "The conductor's 'hapo mbele tutashuka' is a statement of faith, not a destination." },
  { number: 11, title: "Umbrella Magic", lesson: "It doesn't matter if it's been sunshine all day; the moment the first raindrop hits the ground, every second person in Nairobi is suddenly selling umbrellas." },
  { number: 12, title: "The Flyover Mystery", lesson: "Google Maps in Nairobi will tell you to 'take the flyover' when you're already 20 meters past the exit. Prepare for an unplanned trip to Mlolongo." },
  { number: 13, title: "House Hunting", lesson: "Finding a house in Nairobi involves paying a 'viewing fee' to see a mansion and being shown a bedsit with 'scenic views' of the neighbor's balcony." },
  { number: 14, title: "Estate CCTV", lesson: "Nairobi doesn't need high-tech surveillance; we have 'Mama Fua' and the local shopkeeper who know your arrival time better than your spouse does." },
  { number: 15, title: "M-Pesa Moments", lesson: "There is no silence more profound than the one at a supermarket till when the 'Confirming payment' message takes more than 5 seconds." },
  { number: 16, title: "Sunday Vibes", lesson: "Sunday is for Kenyatta Avenue photography, 'Kuku Choma' in Lang'ata, and pretending Monday isn't coming for your soul." },
  { number: 17, title: "The Blue Tick", lesson: "In Nairobi, seen-receipts are optional. If you get blue-ticked on Friday, just assume they've gone to the 'shags' and will reply by Tuesday." },
  { number: 18, title: "Traffic Hawkers", lesson: "You can successfully furnish an entire house, buy a new wardrobe, and get a three-course meal without ever stepping out of your car in Uhuru Highway." },
  { number: 19, title: "Nairobi Nightlife", lesson: "Going for 'one drink' on a Friday usually ends with you eating 'Mutura' at 4 AM while questioning your life choices at a petrol station." },
  { number: 20, title: "The Last Matatu", lesson: "The 'last' matatu at the stage is never actually the last one. It's just the one currently testing your patience while the driver waits for 'mamanani'." },
  { number: 21, title: "The Conductor's Math", lesson: "A matatu conductor can calculate change into 15 different denominations while hanging from a moving vehicle with one hand." },
  { number: 22, title: "Nairobi Dating", lesson: "In Nairobi, 'character development' is a compulsory course offered by the streets. Graduation depends on your resilience." },
  { number: 23, title: "Wait-Time Paradox", lesson: "The time spent waiting for a 14-seater to fill up is directly proportional to how late you already are for your meeting." },
  { number: 24, title: "The Mutura Rule", lesson: "The best Mutura is always found at a place that looks like it hasn't seen a health inspector since 1994." },
  { number: 25, title: "Rainy Day Fare", lesson: "The moment the first drop of rain falls in Nairobi, matatu fares increase by 50%. It's called 'meteorological inflation'." },
  { number: 26, title: "The Manamba Signal", lesson: "A whistle from a manamba can be heard from 3 blocks away, carrying more information than a 5G network." },
  { number: 27, title: "CBD Hustle", lesson: "If you walk too slowly in CBD, someone will try to sell you a belt, a calculator, and a life insurance policy before you reach the next corner." },
  { number: 28, title: "Estate Security", lesson: "Broken glass on a perimeter wall in Nairobi is the original high-security alarm system. It's low-tech but highly effective." },
  { number: 29, title: "The Chapati Secret", lesson: "A Kenyan home's stability is measured by the softness and layers of the Sunday morning chapatis." },
  { number: 30, title: "Matatu Seating", lesson: "The 'sita-sita' rule in a 14-seater is a test of physics where 14 people somehow become 18 through sheer willpower." },
  { number: 31, title: "The 'Chief' Greeting", lesson: "If a stranger calls you 'Chief', 'Boss', or 'Mkubwa', get ready to spend money or lose an argument." },
  { number: 32, title: "Morning Alarm", lesson: "In some estates, you don't need an alarm; the neighbor starting their 'probox' that has no silencer will wake up the entire district." },
  { number: 33, title: "The 'Pricey' Store", lesson: "You know you've 'made it' when you stop checking the price of milk at the supermarket and start buying 'premium' bread." },
  { number: 34, title: "Kanjo Run", lesson: "Seeing a group of men in overalls holding clipboards is the Nairobi version of a horror movie jump-scare for motorists." },
  { number: 35, title: "Nairobi Humidity", lesson: "The air in Nairobi doesn't just have oxygen; it has dreams, dust, and the lingering scent of roasting maize." },
  { number: 36, title: "The 'New' Road", lesson: "A 'new' road in Nairobi stays new for exactly 3 days before a mysterious hole appears to remind you who's boss." },
  { number: 37, title: "Power Outages", lesson: "Total darkness in the middle of a movie is just Nairobi's way of telling you to go to bed and save electricity." },
  { number: 38, title: "The Barber's Wisdom", lesson: "Your barber knows more about your life than your therapist. And he charges much less for the session." },
  { number: 39, title: "Second-Hand Treasure", lesson: "Gikomba is where 'designer' clothes go to get a second chance at life and a 90% discount." },
  { number: 40, title: "The 'Small' Favor", lesson: "When aRelative asks for a 'small' favor, make sure your bank account is ready for a 'large' withdrawal." },
  { number: 41, title: "Matatu Graffitti", lesson: "The art on a matatu is more current than the news. If it's trending, it's on a mudguard by tomorrow." },
  { number: 42, title: "Nairobi Politeness", lesson: "Being told 'Hiyo ni story ingine' means the person isn't going to explain anything and you should stop asking." },
  { number: 43, title: "Uber Navigation", lesson: "An Uber driver asking you 'tupitie wapi?' is a subtle way of asking you to do his job for him." },
  { number: 44, title: "The 'Fixer'", lesson: "A Nairobi 'fundi' will fix your sink but accidentally leave you with a leaking roof. It's a closed-loop economy." },
  { number: 45, title: "Evening Commute", lesson: "The best place to contemplate your existence is in a stationary matatu while watching a snail overtake you on the sidewalk." },
  { number: 46, title: "The 'Kitu Kidogo' Myth", lesson: "Sometimes 'something small' is the only thing standing between you and a very long conversation at a police station." },
  { number: 47, title: "Estate Gossip", lesson: "The fastest way to broadcast a secret is to tell the local 'Askari' and ask him not to tell anyone." },
  { number: 48, title: "The 'Original' Label", lesson: "In Nairobi markets, everything is 'original'. Even the things that haven't been invented yet." },
  { number: 49, title: "Morning Run", lesson: "If you see a Kenyan running at 5 AM, they are either training for Boston or they've just missed the early-bird matatu." },
  { number: 50, title: "Landlord Logic", lesson: "A landlord will ignore your leaking tap for a month but will be at your door at 6 AM on the 1st if the rent is missing." },
  { number: 51, title: "The 'Best' Roast", lesson: "The best roast maize is always sold by a woman who looks like she has survived three world wars and knows all of them." },
  { number: 52, title: "Zebra Crossing", lesson: "In Nairobi, a zebra crossing is just a suggestion. Pedestrians and drivers engage in a daily game of chicken." },
  { number: 53, title: "The 'Fresh' Market", lesson: "Vegetables in Nairobi are 'fresh from the farm', but the journey usually involves a 5-hour ride on top of a truck." },
  { number: 54, title: "Phone Etiquette", lesson: "Picking a call in a matatu while the music is booming requires a special type of sign language combined with shouting." },
  { number: 55, title: "The 'Vybz' Factor", lesson: "A matatu without 'Vybz' is just a glorified bus. Music is the engine, the fuel is the beat." },
  { number: 56, title: "Nairobi Dust", lesson: "You haven't lived in Nairobi if you haven't wiped a layer of dust off your TV that could sustain a small plant." },
  { number: 57, title: "The 'Sale' Sign", lesson: "A 'Closing Down Sale' in Nairobi can last for 5 years. It's a very slow process of going out of business." },
  { number: 58, title: "Matatu Overtaking", lesson: "A matatu driver believes that the laws of physics are merely guidelines that don't apply to him." },
  { number: 59, title: "The 'Side' Hustle", lesson: "Everyone in Nairobi has a side hustle. Even the person who is currently fixing your side hustle." },
  { number: 60, title: "Night Runner", lesson: "The person walking fast behind you at 10 PM isn't a mugger; they're just trying to reach the stage before the last bus leaves." },
  { number: 61, title: "The 'Free' Advice", lesson: "Free advice in a Nairobi bar is usually worth exactly what you paid for it—especially after 11 PM." },
  { number: 62, title: "Shoe Shining", lesson: "A Nairobi shoe shiner will give your shoes a shine so bright you can see your future life choices reflected in them." },
  { number: 63, title: "The 'Urgent' Email", lesson: "An 'urgent' email sent on Friday at 4:30 PM is just a way for your boss to ruin your weekend vibes." },
  { number: 64, title: "Street Style", lesson: "Nairobi street fashion is a chaotic mix of London, New York, and whatever they were clearing out of Gikomba that morning." },
  { number: 65, title: "The 'Stage' Waiter", lesson: "The person who helps you find a matatu at the stage expects a 'thank you' in the form of a 20-shilling coin." },
  { number: 66, title: "Nairobi Coffee", lesson: "The most expensive thing in Nairobi isn't rent; it's a cup of coffee served in a place with 'minimalist' decor." },
  { number: 67, title: "The 'Late' Excuse", lesson: "The 'Matatu broke down' excuse is the 'dog ate my homework' of the Nairobi corporate world." },
  { number: 68, title: "Estate Water", lesson: "Water disappearing on a Saturday morning is just the universe telling you that laundry can wait until Tuesday." },
  { number: 69, title: "The 'Digital' Nairobi", lesson: "Nairobi is digital—we pay for our 'kanda ya moko' with M-Pesa because carrying cash is so 2010." },
  { number: 70, title: "The 'Big' Secret", lesson: "The secret to surviving Nairobi is to act like you know where you're going, even when you're completely lost." },
  { number: 71, title: "Matatu Safety", lesson: "The seatbelts in a matatu are mostly decorative. Their primary function is to get stuck in your clothes." },
  { number: 72, title: "Nairobi Heat", lesson: "The Nairobi sun in January is personal. It follows you into the shade and tells you your problems." },
  { number: 73, title: "The 'Good' News", lesson: "When a Nairobi friend says 'Niko na ka-deal', prepare your business plan or your exit strategy." },
  { number: 74, title: "Estate Children", lesson: "Estate kids playing football are the best scouts. If they stop playing and look at you, you're the main topic of gossip." },
  { number: 75, title: "The 'Fast' Lane", lesson: "The fast lane in Nairobi traffic is actually the sidewalk, but only if you're a boda-boda." },
  { number: 76, title: "Phone Charging", lesson: "Losing 1% of battery in Nairobi is a crisis. People will hunt for a socket like it's hidden gold." },
  { number: 77, title: "The 'Old' Friend", lesson: "An old friend calling you out of the blue usually wants one of three things: a loan, an invitation to a wedding, or to sell you insurance." },
  { number: 78, title: "Nairobi Greenery", lesson: "A park in Nairobi is just a place where people wait for their next appointment while looking at their phones." },
  { number: 79, title: "The 'New' Phone", lesson: "Buying a new phone in CBD requires the security detail of a president and the speed of an Olympic sprinter." },
  { number: 80, title: "Estate Gym", lesson: "Carrying groceries and walking up 5 flights of stairs is the only gym membership most Nairobians need." },
  { number: 81, title: "The 'Morning' Tea", lesson: "Kenyan tea—more milk than water, more sugar than sense. It's the fuel of the nation." },
  { number: 82, title: "Matatu Horn", lesson: "A matatu horn has different languages: 'Get out the way', 'I'm here', 'Hi boss', and 'I'm about to break the law'." },
  { number: 83, title: "Nairobi Puns", lesson: "The best puns are written on the back of trucks. 'Road is family' is a classic." },
  { number: 84, title: "The 'Best' Seat", lesson: "The best seat in a matatu is the one next to the driver, but only if you're prepared to witness a dozen near-death experiences." },
  { number: 85, title: "Nairobi Smog", lesson: "The air in CBD has a specific flavor. It's a blend of exhaust fumes, perfume, and ambition." },
  { number: 86, title: "The 'Quick' Trip", lesson: "A 'quick trip' to the supermarket on a Friday evening is a lie you tell yourself before spending 2 hours in the queue." },
  { number: 87, title: "Estate Lighting", lesson: "Street lights that actually work are a luxury. Most Nairobi nights are lit by the glowing screens of a thousand phones." },
  { number: 88, title: "The 'Secret' Deal", lesson: "A 'deal' that sounds too good to be true in Nairobi is usually someone trying to sell you the same landmark twice." },
  { number: 89, title: "Nairobi Fashion", lesson: "Wearing a suit in a matatu makes everyone think you're either a preacher, a lawyer, or a very well-dressed pickpocket." },
  { number: 90, title: "The 'Last' Chip", lesson: "Sharing chips with a Nairobi friend is a test of character. The last chip is basically a declaration of war." },
  { number: 91, title: "Matatu Aircon", lesson: "Air conditioning in a matatu consists of opening the window slightly and hoping for the best." },
  { number: 92, title: "Nairobi Silence", lesson: "Silence in a Nairobi estate at night is suspicious. It usually means the power is out or someone's dog is about to start barking." },
  { number: 93, title: "The 'Best' Boda", lesson: "A good boda-boda rider is like a pilot. He can navigate a gap the size of a needle with the grace of a gazelle." },
  { number: 94, title: "Nairobi Mornings", lesson: "The city wakes up before the sun. The first sound you hear is the 'kanda ya moko' seller already at work." },
  { number: 95, title: "The 'Fake' Watch", lesson: "A 'Rolex' bought on Parliament Road tells the time perfectly—as long as you don't mind the time being 2 hours late." },
  { number: 96, title: "Nairobi Clouds", lesson: "Dark clouds over Nairobi are the signal for everyone to start walking 5 times faster than usual." },
  { number: 97, title: "The 'Only' Key", lesson: "The person holding the key to the estate gate at 1 AM has more power than the local governor." },
  { number: 98, title: "Nairobi Laughter", lesson: "The sound of laughter in a crowded matatu is the only thing that makes the 2-hour jam bearable." },
  { number: 99, title: "The 'Next' Stop", lesson: "The 'next' stop is never as close as the conductor says it is. Prepare for a mini-marathon." },
  { number: 100, title: "Nairobi Ambition", lesson: "Nairobi is built on dreams. If you can survive here, you can survive anywhere. Even the moon." },
  { number: 101, title: "The 'Kariokoo' Shuffle", lesson: "Navigating Kariokoo with bags is an Olympic sport that combines wrestling, sprinting, and negotiation." },
  { number: 102, title: "Matatu Ethics 2.0", lesson: "If you leave your seat for 2 seconds, you have forfeited your right to sit down for the rest of eternity." },
  { number: 103, title: "Nairobi Rain #2", lesson: "Nairobi rain doesn't fall; it attacks. It comes at an angle designed to bypass your umbrella entirely." },
  { number: 104, title: "The 'Fundi' Lie", lesson: " 'Niko hapo nje' from a fundi means he hasn't even started thinking about coming to your house yet." },
  { number: 105, title: "Estate Garbage", lesson: "The 'garbage guy' arriving early on a Monday is the only reason some people ever wake up before 8 AM." },
  { number: 106, title: "Nairobi Vibes", lesson: "Nairobi isn't just a city; it's a mood, a struggle, and a victory all wrapped in a plastic bag." },
  { number: 107, title: "The 'Lunch' Break", lesson: "A lunch break in CBD is just a 30-minute sprint to find food followed by a 10-minute contest to eat it." },
  { number: 108, title: "Matatu Mirrors", lesson: "A matatu has 20 mirrors, but the driver only uses one—to see if the traffic police are behind him." },
  { number: 109, title: "Nairobi Pigeons", lesson: "The pigeons in CBD have seen things. They walk with the confidence of someone who has a 'guy' in parliament." },
  { number: 110, title: "The 'Secret' Gate", lesson: "Every Nairobi estate has a 'secret' gate that only the residents and the local cat know about." },
  { number: 111, title: "Matatu Overdrive", lesson: "When a matatu driver sees a gap, he takes it. If there isn't a gap, he creates one with the power of his imagination." },
  { number: 112, title: "Nairobi Sounds", lesson: "The sound of a boda-boda at night is either a ride home or a reason to walk a little faster." },
  { number: 113, title: "The 'Free' Wifi", lesson: "Free wifi in Nairobi is like a unicorn. People talk about it, but nobody has actually seen it working for more than 2 minutes." },
  { number: 114, title: "Estate Dogs", lesson: "A dog barking at 3 AM in Nairobi is either a thief or a cat that looked at him the wrong way." },
  { number: 115, title: "Nairobi Traffic #3", lesson: "The only place you can see a Mercedes, a donkey cart, and a group of marathoners in the same lane is Nairobi." },
  { number: 116, title: "The 'Best' Deal", lesson: "A 'deal' in Nairobi usually involves you paying more for something that is worth less, just for the 'experience'." },
  { number: 117, title: "Matatu Lighting", lesson: "The neon lights inside a matatu at night make it look like a mobile disco. It's beautiful and disorienting." },
  { number: 118, title: "Nairobi Ambience", lesson: "The ambience of Nairobi is a mix of car horns, street preachers, and the sound of someone trying to sell you airtime." },
  { number: 119, title: "The 'Last' Word", lesson: "In a Nairobi argument, the person who says 'Wewe ni nani?' first usually loses because they've run out of points." },
  { number: 120, title: "Nairobi Survival", lesson: "To survive Nairobi, you need the heart of a lion, the skin of a rhino, and the patience of a saint waiting for a matatu." },
  { number: 121, title: "The 'Fresh' Bread", lesson: "Bread in Nairobi is only 'fresh' if the steam is still fogging up the plastic. Otherwise, it's just 'vintage' bread." },
  { number: 122, title: "Matatu Speed", lesson: "Speeding matatus don't use brakes; they use 'hope' and the occasional touch of a bumper." },
  { number: 123, title: "Nairobi Networking", lesson: "Networking in Nairobi involves exchanging phone numbers and then never calling each other until you need a loan." },
  { number: 124, title: "The 'New' Area", lesson: "An 'upcoming' area in Nairobi means there are no roads, no water, and your neighbors are all goats." },
  { number: 125, title: "Nairobi Sundays #2", lesson: "Nairobi on Sunday is so quiet you can actually hear your own thoughts—which is usually a sign to go back to sleep." },
  { number: 126, title: "The 'Big' Boss", lesson: "Meeting the 'Big Boss' in Nairobi usually involves waiting for 3 hours and then being told he's 'in a meeting' for the rest of the day." },
  { number: 127, title: "Matatu Ethics #3", lesson: "The person in the middle seat is the unofficial mediator for all arguments between the conductor and the passengers." },
  { number: 128, title: "Nairobi Rain #3", lesson: "Rain in Nairobi is the only thing that can turn a 20-minute drive into a 4-hour journey. It's like magic, but bad." },
  { number: 129, title: "The 'Small' Town", lesson: "Nairobi is just a collection of small towns connected by traffic jams and mutual suspicion." },
  { number: 130, title: "Nairobi Dreams", lesson: "Everyone in Nairobi is chasing a dream. Some are chasing money, some are chasing fame, and most are just chasing the last bus." },
  { number: 131, title: "The 'Cold' Morning", lesson: "A cold morning in Nairobi is nature's way of telling you that your 'duvet' is your best friend." },
  { number: 132, title: "Matatu Bass", lesson: "The bass in a matatu doesn't just play music; it reshapes your internal organs to the rhythm of the beat." },
  { number: 133, title: "Nairobi Lingo", lesson: "English is for the office, Swahili is for the street, and Sheng is for when you want to make sure your parents don't understand you." },
  { number: 134, title: "The 'Best' Chapo", lesson: "The best chapati is the one you didn't have to cook yourself. It tastes like freedom and oil." },
  { number: 135, title: "Estate Lights #2", lesson: "A working street light in your estate is a sign that the elections are coming soon." },
  { number: 136, title: "Nairobi Fashion #2", lesson: "Sunglasses at night are the ultimate 'I'm a celebrity in my own mind' accessory in Nairobi clubs." },
  { number: 137, title: "The 'Only' Way", lesson: "The 'only' way to get things done in Nairobi is to know someone who knows someone who knows the person in charge." },
  { number: 138, title: "Matatu Drivers #2", lesson: "A matatu driver's favorite color is 'yellow'—because it's the color of a gap he's about to fly through." },
  { number: 139, title: "Nairobi Vibes #2", lesson: "The vibe of the city changes at 6 PM. It goes from 'Hustle' to 'Survival' in the blink of an eye." },
  { number: 140, title: "The 'Final' Word", lesson: "In Nairobi, the final word is always 'M-Pesa'. Everything else is just conversation." },
  { number: 141, title: "Nairobi Birds", lesson: "The birds in Nairobi don't sing; they debate. Usually about who gets the most crumbs at the outdoor cafe." },
  { number: 142, title: "The 'Broken' Escalator", lesson: "A broken escalator in a Nairobi mall is just a 'stairs' with extra steps and a sense of disappointment." },
  { number: 143, title: "Matatu Seating #2", lesson: "The seat behind the driver is either the safest or the most terrifying place on earth, depending on his mood." },
  { number: 144, title: "Nairobi Rain #4", lesson: "When it rains in Nairobi, the drainage system decides to take a sabbatical. High-waist boots are a necessity, not a choice." },
  { number: 145, title: "The 'Legendary' Meat", lesson: "The legendary status of a 'choma' joint is determined by the number of cars parked outside on a Tuesday evening." },
  { number: 146, title: "Nairobi Mornings #2", lesson: "The smell of roasting coffee near CBD at 7 AM is the only thing that makes the commute feel worth it." },
  { number: 147, title: "The 'Last' Token", lesson: "The panic when your KPLC tokens hit '1.00' is the most intense feeling known to mankind in Nairobi." },
  { number: 148, title: "Matatu Art", lesson: "Matatu art is the gallery of the streets. It's where Tupac, Messi, and local legends live together in harmony." },
  { number: 149, title: "Nairobi Hearts", lesson: "A Nairobi heart is like the city: tough on the outside, vibrant on the inside, and always ready for a deal." },
  { number: 150, title: "The Nairobi Way", lesson: "There is no wrong way to do Nairobi, as long as you end the day with a full stomach and a working phone." }
];

